### ISSUE TITLE
Truncated Event Details on Calendar

### ISSUE THREAD

**Issue by vinceJM** [llacoste/ccc#23]
Description for events on certain days are truncated. (e.g., April 13)

**Comment by vinceJM** [comment]
when i clicked the event for april 13, it shows me 
![screen shot 2015-02-06 at 14 00 08](https://cloud.githubusercontent.com/assets/5991993/6086562/7cb09a82-ae08-11e4-805a-3ed6105b9084.png)

**Comment by llacoste** [comment]
This should be corrected with:

https://github.com/llacoste/ccc/pull/26 

I need to release the update, drop the table, then repopulate.

Thanks!

**Comment by llacoste** [comment]
I will need to use a different source. Try as I might I cannot get rid of the html embedded in the text.

**Comment by llacoste** [comment]
This has been corrected, finally.
